"""empty message

Revision ID: 49cc971eefd6
Revises: 
Create Date: 2023-04-10 13:50:52.335057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49cc971eefd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('film_simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('film', sa.String(), nullable=True),
    sa.Column('dynam_range', sa.String(), nullable=True),
    sa.Column('highlight', sa.String(), nullable=True),
    sa.Column('shadow', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('noise_reduction', sa.String(), nullable=True),
    sa.Column('sharpening', sa.String(), nullable=True),
    sa.Column('clarity', sa.String(), nullable=True),
    sa.Column('grain', sa.String(), nullable=True),
    sa.Column('color_chrome', sa.String(), nullable=True),
    sa.Column('color_chrome_blue', sa.String(), nullable=True),
    sa.Column('white_balance', sa.String(), nullable=True),
    sa.Column('iso', sa.String(), nullable=True),
    sa.Column('exposure', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('film', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('cinebloom_10', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_photos_camera_id_cameras')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_photos_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('film_simulation_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('film_simulation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_simulation_id'], ['film_simulations.id'], name=op.f('fk_film_simulation_photos_film_simulation_id_film_simulations')),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name=op.f('fk_film_simulation_photos_photo_id_photos')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film_simulation_photos')
    op.drop_table('photos')
    op.drop_table('users')
    op.drop_table('film_simulations')
    op.drop_table('client_contacts')
    op.drop_table('cameras')
    # ### end Alembic commands ###
